-- Widen AnchorRecordID from NVARCHAR(100) → NVARCHAR(450) on every table that persists an anchor's
-- canonical record id: Score, ScoreHistory, ScoreBandTransition.
--
-- Why: composite (multi-column) anchor keys serialize their id as an escaped join of the key column
-- values (see anchorKey.ts / canonicalAnchorId). A single GUID fits in 100 chars, but a 3+-column
-- GUID key or a long-varchar composite runs well past it. At 100 the id would silently truncate —
-- either failing to match the caller's full AnchorKey.id (the anchor scores as no-data) or colliding
-- two anchors that share a 100-char prefix. The same id also shreds through the factor query's
-- OPENJSON `id` column (widened to 450 in factorSql.ts), so the two must agree.
--
-- 450 is MJ's standard width for an INDEXED record-key column (450 chars = the largest nonclustered
-- index key SQL Server allows; MJ uses NVARCHAR(450) for exactly this on SourceRecordID/RecordID and
-- friends). AnchorRecordID participates in UQ_Score_ModelAnchorRecord and IX_ScoreHistory_..., so it
-- must stay index-safe — 450 does. AnchorRecordKeyJSON (the type-faithful key) is already NVARCHAR(MAX).
--
-- ALTER COLUMN can't touch a column while an index references it, so we drop the two dependents,
-- widen all three columns, then recreate the index/constraint exactly as the Initial Schema defined
-- them (ScoreBandTransition.AnchorRecordID has no index, so it widens directly).

ALTER TABLE ${flyway:defaultSchema}.Score DROP CONSTRAINT UQ_Score_ModelAnchorRecord;
GO
DROP INDEX IX_ScoreHistory_Model_Anchor_AsOf ON ${flyway:defaultSchema}.ScoreHistory;
GO

ALTER TABLE ${flyway:defaultSchema}.Score ALTER COLUMN AnchorRecordID NVARCHAR(450) NOT NULL;
GO
ALTER TABLE ${flyway:defaultSchema}.ScoreHistory ALTER COLUMN AnchorRecordID NVARCHAR(450) NOT NULL;
GO
ALTER TABLE ${flyway:defaultSchema}.ScoreBandTransition ALTER COLUMN AnchorRecordID NVARCHAR(450) NOT NULL;
GO

ALTER TABLE ${flyway:defaultSchema}.Score
    ADD CONSTRAINT UQ_Score_ModelAnchorRecord UNIQUE (ScoreModelID, AnchorRecordID);
GO
CREATE INDEX IX_ScoreHistory_Model_Anchor_AsOf
    ON ${flyway:defaultSchema}.ScoreHistory (ScoreModelID, AnchorRecordID, AsOfDate);
GO

-- ============================================================================
-- CodeGen output — regenerated Score / ScoreHistory / ScoreBandTransition views,
-- CRUD procs, FK indexes, and entity-field metadata to reflect the widened
-- AnchorRecordID (nvarchar(450)). Generated by 'mj codegen' against the clean Sonar
-- schema and appended per the migration convention (see the Initial Schema migration's
-- embedded codegen section). The metadata-sync EXECs pull the new column length into the
-- EntityField catalog; the CRUD procs pick up the wider @AnchorRecordID parameter.
-- ============================================================================

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* Index for Foreign Keys for ScoreBandTransition */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Band Transitions
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ScoreModelID in table ScoreBandTransition
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreBandTransition_ScoreModelID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreBandTransition]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreBandTransition_ScoreModelID ON [${flyway:defaultSchema}].[ScoreBandTransition] ([ScoreModelID]);

-- Index for foreign key FromBandID in table ScoreBandTransition
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreBandTransition_FromBandID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreBandTransition]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreBandTransition_FromBandID ON [${flyway:defaultSchema}].[ScoreBandTransition] ([FromBandID]);

-- Index for foreign key ToBandID in table ScoreBandTransition
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreBandTransition_ToBandID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreBandTransition]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreBandTransition_ToBandID ON [${flyway:defaultSchema}].[ScoreBandTransition] ([ToBandID]);

-- Index for foreign key RecomputeRunID in table ScoreBandTransition
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreBandTransition_RecomputeRunID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreBandTransition]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreBandTransition_RecomputeRunID ON [${flyway:defaultSchema}].[ScoreBandTransition] ([RecomputeRunID]);

/* Base View SQL for MJ_BizApps_Sonar: Score Band Transitions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Band Transitions
-- Item: vwScoreBandTransitions
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Sonar: Score Band Transitions
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ScoreBandTransition
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwScoreBandTransitions]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwScoreBandTransitions];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwScoreBandTransitions]
AS
SELECT
    s.*,
    mjBizAppsSonarScoreModel_ScoreModelID.[Name] AS [ScoreModel]
FROM
    [${flyway:defaultSchema}].[ScoreBandTransition] AS s
INNER JOIN
    [${flyway:defaultSchema}].[ScoreModel] AS mjBizAppsSonarScoreModel_ScoreModelID
  ON
    [s].[ScoreModelID] = mjBizAppsSonarScoreModel_ScoreModelID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwScoreBandTransitions] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Sonar: Score Band Transitions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Band Transitions
-- Item: Permissions for vwScoreBandTransitions
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwScoreBandTransitions] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Sonar: Score Band Transitions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Band Transitions
-- Item: spCreateScoreBandTransition
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ScoreBandTransition
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateScoreBandTransition]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateScoreBandTransition];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateScoreBandTransition]
    @ID uniqueidentifier = NULL,
    @ScoreModelID uniqueidentifier,
    @AnchorRecordID nvarchar(450),
    @FromBandID_Clear bit = 0,
    @FromBandID uniqueidentifier = NULL,
    @ToBandID_Clear bit = 0,
    @ToBandID uniqueidentifier = NULL,
    @Direction_Clear bit = 0,
    @Direction nvarchar(12) = NULL,
    @OccurredAt datetime2 = NULL,
    @RecomputeRunID_Clear bit = 0,
    @RecomputeRunID uniqueidentifier = NULL,
    @Handled bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ScoreBandTransition]
            (
                [ID],
                [ScoreModelID],
                [AnchorRecordID],
                [FromBandID],
                [ToBandID],
                [Direction],
                [OccurredAt],
                [RecomputeRunID],
                [Handled]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ScoreModelID,
                @AnchorRecordID,
                CASE WHEN @FromBandID_Clear = 1 THEN NULL ELSE ISNULL(@FromBandID, NULL) END,
                CASE WHEN @ToBandID_Clear = 1 THEN NULL ELSE ISNULL(@ToBandID, NULL) END,
                CASE WHEN @Direction_Clear = 1 THEN NULL ELSE ISNULL(@Direction, NULL) END,
                ISNULL(@OccurredAt, getutcdate()),
                CASE WHEN @RecomputeRunID_Clear = 1 THEN NULL ELSE ISNULL(@RecomputeRunID, NULL) END,
                ISNULL(@Handled, 0)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ScoreBandTransition]
            (
                [ScoreModelID],
                [AnchorRecordID],
                [FromBandID],
                [ToBandID],
                [Direction],
                [OccurredAt],
                [RecomputeRunID],
                [Handled]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ScoreModelID,
                @AnchorRecordID,
                CASE WHEN @FromBandID_Clear = 1 THEN NULL ELSE ISNULL(@FromBandID, NULL) END,
                CASE WHEN @ToBandID_Clear = 1 THEN NULL ELSE ISNULL(@ToBandID, NULL) END,
                CASE WHEN @Direction_Clear = 1 THEN NULL ELSE ISNULL(@Direction, NULL) END,
                ISNULL(@OccurredAt, getutcdate()),
                CASE WHEN @RecomputeRunID_Clear = 1 THEN NULL ELSE ISNULL(@RecomputeRunID, NULL) END,
                ISNULL(@Handled, 0)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwScoreBandTransitions] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateScoreBandTransition] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Sonar: Score Band Transitions */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateScoreBandTransition] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Sonar: Score Band Transitions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Band Transitions
-- Item: spUpdateScoreBandTransition
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ScoreBandTransition
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateScoreBandTransition]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateScoreBandTransition];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateScoreBandTransition]
    @ID uniqueidentifier,
    @ScoreModelID uniqueidentifier = NULL,
    @AnchorRecordID nvarchar(450) = NULL,
    @FromBandID_Clear bit = 0,
    @FromBandID uniqueidentifier = NULL,
    @ToBandID_Clear bit = 0,
    @ToBandID uniqueidentifier = NULL,
    @Direction_Clear bit = 0,
    @Direction nvarchar(12) = NULL,
    @OccurredAt datetime2 = NULL,
    @RecomputeRunID_Clear bit = 0,
    @RecomputeRunID uniqueidentifier = NULL,
    @Handled bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ScoreBandTransition]
    SET
        [ScoreModelID] = ISNULL(@ScoreModelID, [ScoreModelID]),
        [AnchorRecordID] = ISNULL(@AnchorRecordID, [AnchorRecordID]),
        [FromBandID] = CASE WHEN @FromBandID_Clear = 1 THEN NULL ELSE ISNULL(@FromBandID, [FromBandID]) END,
        [ToBandID] = CASE WHEN @ToBandID_Clear = 1 THEN NULL ELSE ISNULL(@ToBandID, [ToBandID]) END,
        [Direction] = CASE WHEN @Direction_Clear = 1 THEN NULL ELSE ISNULL(@Direction, [Direction]) END,
        [OccurredAt] = ISNULL(@OccurredAt, [OccurredAt]),
        [RecomputeRunID] = CASE WHEN @RecomputeRunID_Clear = 1 THEN NULL ELSE ISNULL(@RecomputeRunID, [RecomputeRunID]) END,
        [Handled] = ISNULL(@Handled, [Handled])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwScoreBandTransitions] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwScoreBandTransitions]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateScoreBandTransition] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ScoreBandTransition table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateScoreBandTransition]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateScoreBandTransition];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateScoreBandTransition
ON [${flyway:defaultSchema}].[ScoreBandTransition]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ScoreBandTransition]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ScoreBandTransition] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Sonar: Score Band Transitions */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateScoreBandTransition] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Sonar: Score Band Transitions */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Band Transitions
-- Item: spDeleteScoreBandTransition
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ScoreBandTransition
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteScoreBandTransition]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteScoreBandTransition];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteScoreBandTransition]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ScoreBandTransition]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteScoreBandTransition] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Sonar: Score Band Transitions */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteScoreBandTransition] TO [cdp_Developer], [cdp_Integration];

/* Index for Foreign Keys for ScoreHistory */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Histories
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ScoreModelID in table ScoreHistory
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreHistory_ScoreModelID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreHistory]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreHistory_ScoreModelID ON [${flyway:defaultSchema}].[ScoreHistory] ([ScoreModelID]);

-- Index for foreign key ScoreModelVersionID in table ScoreHistory
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreHistory_ScoreModelVersionID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreHistory]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreHistory_ScoreModelVersionID ON [${flyway:defaultSchema}].[ScoreHistory] ([ScoreModelVersionID]);

-- Index for foreign key AnchorEntityID in table ScoreHistory
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreHistory_AnchorEntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreHistory]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreHistory_AnchorEntityID ON [${flyway:defaultSchema}].[ScoreHistory] ([AnchorEntityID]);

-- Index for foreign key BandID in table ScoreHistory
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ScoreHistory_BandID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ScoreHistory]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ScoreHistory_BandID ON [${flyway:defaultSchema}].[ScoreHistory] ([BandID]);

/* Base View SQL for MJ_BizApps_Sonar: Score Histories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Histories
-- Item: vwScoreHistories
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Sonar: Score Histories
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ScoreHistory
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwScoreHistories]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwScoreHistories];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwScoreHistories]
AS
SELECT
    s.*,
    mjBizAppsSonarScoreModel_ScoreModelID.[Name] AS [ScoreModel],
    MJEntity_AnchorEntityID.[Name] AS [AnchorEntity]
FROM
    [${flyway:defaultSchema}].[ScoreHistory] AS s
INNER JOIN
    [${flyway:defaultSchema}].[ScoreModel] AS mjBizAppsSonarScoreModel_ScoreModelID
  ON
    [s].[ScoreModelID] = mjBizAppsSonarScoreModel_ScoreModelID.[ID]
INNER JOIN
    [${mjSchema}].[Entity] AS MJEntity_AnchorEntityID
  ON
    [s].[AnchorEntityID] = MJEntity_AnchorEntityID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwScoreHistories] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Sonar: Score Histories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Histories
-- Item: Permissions for vwScoreHistories
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwScoreHistories] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Sonar: Score Histories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Histories
-- Item: spCreateScoreHistory
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ScoreHistory
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateScoreHistory]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateScoreHistory];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateScoreHistory]
    @ID uniqueidentifier = NULL,
    @ScoreModelID uniqueidentifier,
    @ScoreModelVersionID uniqueidentifier,
    @AnchorEntityID uniqueidentifier,
    @AnchorRecordID nvarchar(450),
    @NormalizedScore_Clear bit = 0,
    @NormalizedScore decimal(9, 4) = NULL,
    @BandID_Clear bit = 0,
    @BandID uniqueidentifier = NULL,
    @AsOfDate_Clear bit = 0,
    @AsOfDate datetime2 = NULL,
    @ComputedAt datetime2 = NULL,
    @DataCompleteness_Clear bit = 0,
    @DataCompleteness decimal(5, 4) = NULL,
    @Confidence_Clear bit = 0,
    @Confidence decimal(5, 4) = NULL,
    @ContributionsJSON_Clear bit = 0,
    @ContributionsJSON nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ScoreHistory]
            (
                [ID],
                [ScoreModelID],
                [ScoreModelVersionID],
                [AnchorEntityID],
                [AnchorRecordID],
                [NormalizedScore],
                [BandID],
                [AsOfDate],
                [ComputedAt],
                [DataCompleteness],
                [Confidence],
                [ContributionsJSON]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ScoreModelID,
                @ScoreModelVersionID,
                @AnchorEntityID,
                @AnchorRecordID,
                CASE WHEN @NormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@NormalizedScore, NULL) END,
                CASE WHEN @BandID_Clear = 1 THEN NULL ELSE ISNULL(@BandID, NULL) END,
                CASE WHEN @AsOfDate_Clear = 1 THEN NULL ELSE ISNULL(@AsOfDate, NULL) END,
                ISNULL(@ComputedAt, getutcdate()),
                CASE WHEN @DataCompleteness_Clear = 1 THEN NULL ELSE ISNULL(@DataCompleteness, NULL) END,
                CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, NULL) END,
                CASE WHEN @ContributionsJSON_Clear = 1 THEN NULL ELSE ISNULL(@ContributionsJSON, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ScoreHistory]
            (
                [ScoreModelID],
                [ScoreModelVersionID],
                [AnchorEntityID],
                [AnchorRecordID],
                [NormalizedScore],
                [BandID],
                [AsOfDate],
                [ComputedAt],
                [DataCompleteness],
                [Confidence],
                [ContributionsJSON]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ScoreModelID,
                @ScoreModelVersionID,
                @AnchorEntityID,
                @AnchorRecordID,
                CASE WHEN @NormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@NormalizedScore, NULL) END,
                CASE WHEN @BandID_Clear = 1 THEN NULL ELSE ISNULL(@BandID, NULL) END,
                CASE WHEN @AsOfDate_Clear = 1 THEN NULL ELSE ISNULL(@AsOfDate, NULL) END,
                ISNULL(@ComputedAt, getutcdate()),
                CASE WHEN @DataCompleteness_Clear = 1 THEN NULL ELSE ISNULL(@DataCompleteness, NULL) END,
                CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, NULL) END,
                CASE WHEN @ContributionsJSON_Clear = 1 THEN NULL ELSE ISNULL(@ContributionsJSON, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwScoreHistories] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateScoreHistory] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Sonar: Score Histories */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateScoreHistory] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Sonar: Score Histories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Histories
-- Item: spUpdateScoreHistory
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ScoreHistory
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateScoreHistory]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateScoreHistory];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateScoreHistory]
    @ID uniqueidentifier,
    @ScoreModelID uniqueidentifier = NULL,
    @ScoreModelVersionID uniqueidentifier = NULL,
    @AnchorEntityID uniqueidentifier = NULL,
    @AnchorRecordID nvarchar(450) = NULL,
    @NormalizedScore_Clear bit = 0,
    @NormalizedScore decimal(9, 4) = NULL,
    @BandID_Clear bit = 0,
    @BandID uniqueidentifier = NULL,
    @AsOfDate_Clear bit = 0,
    @AsOfDate datetime2 = NULL,
    @ComputedAt datetime2 = NULL,
    @DataCompleteness_Clear bit = 0,
    @DataCompleteness decimal(5, 4) = NULL,
    @Confidence_Clear bit = 0,
    @Confidence decimal(5, 4) = NULL,
    @ContributionsJSON_Clear bit = 0,
    @ContributionsJSON nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ScoreHistory]
    SET
        [ScoreModelID] = ISNULL(@ScoreModelID, [ScoreModelID]),
        [ScoreModelVersionID] = ISNULL(@ScoreModelVersionID, [ScoreModelVersionID]),
        [AnchorEntityID] = ISNULL(@AnchorEntityID, [AnchorEntityID]),
        [AnchorRecordID] = ISNULL(@AnchorRecordID, [AnchorRecordID]),
        [NormalizedScore] = CASE WHEN @NormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@NormalizedScore, [NormalizedScore]) END,
        [BandID] = CASE WHEN @BandID_Clear = 1 THEN NULL ELSE ISNULL(@BandID, [BandID]) END,
        [AsOfDate] = CASE WHEN @AsOfDate_Clear = 1 THEN NULL ELSE ISNULL(@AsOfDate, [AsOfDate]) END,
        [ComputedAt] = ISNULL(@ComputedAt, [ComputedAt]),
        [DataCompleteness] = CASE WHEN @DataCompleteness_Clear = 1 THEN NULL ELSE ISNULL(@DataCompleteness, [DataCompleteness]) END,
        [Confidence] = CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, [Confidence]) END,
        [ContributionsJSON] = CASE WHEN @ContributionsJSON_Clear = 1 THEN NULL ELSE ISNULL(@ContributionsJSON, [ContributionsJSON]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwScoreHistories] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwScoreHistories]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateScoreHistory] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ScoreHistory table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateScoreHistory]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateScoreHistory];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateScoreHistory
ON [${flyway:defaultSchema}].[ScoreHistory]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ScoreHistory]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ScoreHistory] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Sonar: Score Histories */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateScoreHistory] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Sonar: Score Histories */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Score Histories
-- Item: spDeleteScoreHistory
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ScoreHistory
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteScoreHistory]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteScoreHistory];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteScoreHistory]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ScoreHistory]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteScoreHistory] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Sonar: Score Histories */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteScoreHistory] TO [cdp_Developer], [cdp_Integration];

/* Index for Foreign Keys for Score */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Scores
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ScoreModelID in table Score
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Score_ScoreModelID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Score]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Score_ScoreModelID ON [${flyway:defaultSchema}].[Score] ([ScoreModelID]);

-- Index for foreign key ScoreModelVersionID in table Score
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Score_ScoreModelVersionID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Score]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Score_ScoreModelVersionID ON [${flyway:defaultSchema}].[Score] ([ScoreModelVersionID]);

-- Index for foreign key AnchorEntityID in table Score
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Score_AnchorEntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Score]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Score_AnchorEntityID ON [${flyway:defaultSchema}].[Score] ([AnchorEntityID]);

-- Index for foreign key BandID in table Score
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Score_BandID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Score]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Score_BandID ON [${flyway:defaultSchema}].[Score] ([BandID]);

-- Index for foreign key PreviousBandID in table Score
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Score_PreviousBandID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Score]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Score_PreviousBandID ON [${flyway:defaultSchema}].[Score] ([PreviousBandID]);

/* Base View SQL for MJ_BizApps_Sonar: Scores */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Scores
-- Item: vwScores
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Sonar: Scores
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  Score
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwScores]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwScores];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwScores]
AS
SELECT
    s.*,
    mjBizAppsSonarScoreModel_ScoreModelID.[Name] AS [ScoreModel],
    MJEntity_AnchorEntityID.[Name] AS [AnchorEntity]
FROM
    [${flyway:defaultSchema}].[Score] AS s
INNER JOIN
    [${flyway:defaultSchema}].[ScoreModel] AS mjBizAppsSonarScoreModel_ScoreModelID
  ON
    [s].[ScoreModelID] = mjBizAppsSonarScoreModel_ScoreModelID.[ID]
INNER JOIN
    [${mjSchema}].[Entity] AS MJEntity_AnchorEntityID
  ON
    [s].[AnchorEntityID] = MJEntity_AnchorEntityID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwScores] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Sonar: Scores */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Scores
-- Item: Permissions for vwScores
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwScores] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Sonar: Scores */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Scores
-- Item: spCreateScore
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Score
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateScore]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateScore];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateScore]
    @ID uniqueidentifier = NULL,
    @ScoreModelID uniqueidentifier,
    @ScoreModelVersionID uniqueidentifier,
    @AnchorEntityID uniqueidentifier,
    @AnchorRecordID nvarchar(450),
    @AnchorRecordKeyJSON_Clear bit = 0,
    @AnchorRecordKeyJSON nvarchar(MAX) = NULL,
    @RawScore_Clear bit = 0,
    @RawScore decimal(12, 4) = NULL,
    @NormalizedScore_Clear bit = 0,
    @NormalizedScore decimal(9, 4) = NULL,
    @BandID_Clear bit = 0,
    @BandID uniqueidentifier = NULL,
    @PreviousNormalizedScore_Clear bit = 0,
    @PreviousNormalizedScore decimal(9, 4) = NULL,
    @PreviousBandID_Clear bit = 0,
    @PreviousBandID uniqueidentifier = NULL,
    @Delta_Clear bit = 0,
    @Delta decimal(9, 4) = NULL,
    @TrendDirection_Clear bit = 0,
    @TrendDirection nvarchar(8) = NULL,
    @TrendSlope_Clear bit = 0,
    @TrendSlope decimal(12, 6) = NULL,
    @Confidence_Clear bit = 0,
    @Confidence decimal(5, 4) = NULL,
    @DataCompleteness_Clear bit = 0,
    @DataCompleteness decimal(5, 4) = NULL,
    @ComputedAt datetime2 = NULL,
    @AsOfDate_Clear bit = 0,
    @AsOfDate datetime2 = NULL,
    @NextRecomputeAt_Clear bit = 0,
    @NextRecomputeAt datetime2 = NULL,
    @IsStale bit = NULL,
    @ExplanationSummary_Clear bit = 0,
    @ExplanationSummary nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Score]
            (
                [ID],
                [ScoreModelID],
                [ScoreModelVersionID],
                [AnchorEntityID],
                [AnchorRecordID],
                [AnchorRecordKeyJSON],
                [RawScore],
                [NormalizedScore],
                [BandID],
                [PreviousNormalizedScore],
                [PreviousBandID],
                [Delta],
                [TrendDirection],
                [TrendSlope],
                [Confidence],
                [DataCompleteness],
                [ComputedAt],
                [AsOfDate],
                [NextRecomputeAt],
                [IsStale],
                [ExplanationSummary]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ScoreModelID,
                @ScoreModelVersionID,
                @AnchorEntityID,
                @AnchorRecordID,
                CASE WHEN @AnchorRecordKeyJSON_Clear = 1 THEN NULL ELSE ISNULL(@AnchorRecordKeyJSON, NULL) END,
                CASE WHEN @RawScore_Clear = 1 THEN NULL ELSE ISNULL(@RawScore, NULL) END,
                CASE WHEN @NormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@NormalizedScore, NULL) END,
                CASE WHEN @BandID_Clear = 1 THEN NULL ELSE ISNULL(@BandID, NULL) END,
                CASE WHEN @PreviousNormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@PreviousNormalizedScore, NULL) END,
                CASE WHEN @PreviousBandID_Clear = 1 THEN NULL ELSE ISNULL(@PreviousBandID, NULL) END,
                CASE WHEN @Delta_Clear = 1 THEN NULL ELSE ISNULL(@Delta, NULL) END,
                CASE WHEN @TrendDirection_Clear = 1 THEN NULL ELSE ISNULL(@TrendDirection, NULL) END,
                CASE WHEN @TrendSlope_Clear = 1 THEN NULL ELSE ISNULL(@TrendSlope, NULL) END,
                CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, NULL) END,
                CASE WHEN @DataCompleteness_Clear = 1 THEN NULL ELSE ISNULL(@DataCompleteness, NULL) END,
                ISNULL(@ComputedAt, getutcdate()),
                CASE WHEN @AsOfDate_Clear = 1 THEN NULL ELSE ISNULL(@AsOfDate, NULL) END,
                CASE WHEN @NextRecomputeAt_Clear = 1 THEN NULL ELSE ISNULL(@NextRecomputeAt, NULL) END,
                ISNULL(@IsStale, 0),
                CASE WHEN @ExplanationSummary_Clear = 1 THEN NULL ELSE ISNULL(@ExplanationSummary, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Score]
            (
                [ScoreModelID],
                [ScoreModelVersionID],
                [AnchorEntityID],
                [AnchorRecordID],
                [AnchorRecordKeyJSON],
                [RawScore],
                [NormalizedScore],
                [BandID],
                [PreviousNormalizedScore],
                [PreviousBandID],
                [Delta],
                [TrendDirection],
                [TrendSlope],
                [Confidence],
                [DataCompleteness],
                [ComputedAt],
                [AsOfDate],
                [NextRecomputeAt],
                [IsStale],
                [ExplanationSummary]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ScoreModelID,
                @ScoreModelVersionID,
                @AnchorEntityID,
                @AnchorRecordID,
                CASE WHEN @AnchorRecordKeyJSON_Clear = 1 THEN NULL ELSE ISNULL(@AnchorRecordKeyJSON, NULL) END,
                CASE WHEN @RawScore_Clear = 1 THEN NULL ELSE ISNULL(@RawScore, NULL) END,
                CASE WHEN @NormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@NormalizedScore, NULL) END,
                CASE WHEN @BandID_Clear = 1 THEN NULL ELSE ISNULL(@BandID, NULL) END,
                CASE WHEN @PreviousNormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@PreviousNormalizedScore, NULL) END,
                CASE WHEN @PreviousBandID_Clear = 1 THEN NULL ELSE ISNULL(@PreviousBandID, NULL) END,
                CASE WHEN @Delta_Clear = 1 THEN NULL ELSE ISNULL(@Delta, NULL) END,
                CASE WHEN @TrendDirection_Clear = 1 THEN NULL ELSE ISNULL(@TrendDirection, NULL) END,
                CASE WHEN @TrendSlope_Clear = 1 THEN NULL ELSE ISNULL(@TrendSlope, NULL) END,
                CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, NULL) END,
                CASE WHEN @DataCompleteness_Clear = 1 THEN NULL ELSE ISNULL(@DataCompleteness, NULL) END,
                ISNULL(@ComputedAt, getutcdate()),
                CASE WHEN @AsOfDate_Clear = 1 THEN NULL ELSE ISNULL(@AsOfDate, NULL) END,
                CASE WHEN @NextRecomputeAt_Clear = 1 THEN NULL ELSE ISNULL(@NextRecomputeAt, NULL) END,
                ISNULL(@IsStale, 0),
                CASE WHEN @ExplanationSummary_Clear = 1 THEN NULL ELSE ISNULL(@ExplanationSummary, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwScores] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateScore] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Sonar: Scores */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateScore] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Sonar: Scores */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Scores
-- Item: spUpdateScore
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Score
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateScore]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateScore];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateScore]
    @ID uniqueidentifier,
    @ScoreModelID uniqueidentifier = NULL,
    @ScoreModelVersionID uniqueidentifier = NULL,
    @AnchorEntityID uniqueidentifier = NULL,
    @AnchorRecordID nvarchar(450) = NULL,
    @AnchorRecordKeyJSON_Clear bit = 0,
    @AnchorRecordKeyJSON nvarchar(MAX) = NULL,
    @RawScore_Clear bit = 0,
    @RawScore decimal(12, 4) = NULL,
    @NormalizedScore_Clear bit = 0,
    @NormalizedScore decimal(9, 4) = NULL,
    @BandID_Clear bit = 0,
    @BandID uniqueidentifier = NULL,
    @PreviousNormalizedScore_Clear bit = 0,
    @PreviousNormalizedScore decimal(9, 4) = NULL,
    @PreviousBandID_Clear bit = 0,
    @PreviousBandID uniqueidentifier = NULL,
    @Delta_Clear bit = 0,
    @Delta decimal(9, 4) = NULL,
    @TrendDirection_Clear bit = 0,
    @TrendDirection nvarchar(8) = NULL,
    @TrendSlope_Clear bit = 0,
    @TrendSlope decimal(12, 6) = NULL,
    @Confidence_Clear bit = 0,
    @Confidence decimal(5, 4) = NULL,
    @DataCompleteness_Clear bit = 0,
    @DataCompleteness decimal(5, 4) = NULL,
    @ComputedAt datetime2 = NULL,
    @AsOfDate_Clear bit = 0,
    @AsOfDate datetime2 = NULL,
    @NextRecomputeAt_Clear bit = 0,
    @NextRecomputeAt datetime2 = NULL,
    @IsStale bit = NULL,
    @ExplanationSummary_Clear bit = 0,
    @ExplanationSummary nvarchar(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Score]
    SET
        [ScoreModelID] = ISNULL(@ScoreModelID, [ScoreModelID]),
        [ScoreModelVersionID] = ISNULL(@ScoreModelVersionID, [ScoreModelVersionID]),
        [AnchorEntityID] = ISNULL(@AnchorEntityID, [AnchorEntityID]),
        [AnchorRecordID] = ISNULL(@AnchorRecordID, [AnchorRecordID]),
        [AnchorRecordKeyJSON] = CASE WHEN @AnchorRecordKeyJSON_Clear = 1 THEN NULL ELSE ISNULL(@AnchorRecordKeyJSON, [AnchorRecordKeyJSON]) END,
        [RawScore] = CASE WHEN @RawScore_Clear = 1 THEN NULL ELSE ISNULL(@RawScore, [RawScore]) END,
        [NormalizedScore] = CASE WHEN @NormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@NormalizedScore, [NormalizedScore]) END,
        [BandID] = CASE WHEN @BandID_Clear = 1 THEN NULL ELSE ISNULL(@BandID, [BandID]) END,
        [PreviousNormalizedScore] = CASE WHEN @PreviousNormalizedScore_Clear = 1 THEN NULL ELSE ISNULL(@PreviousNormalizedScore, [PreviousNormalizedScore]) END,
        [PreviousBandID] = CASE WHEN @PreviousBandID_Clear = 1 THEN NULL ELSE ISNULL(@PreviousBandID, [PreviousBandID]) END,
        [Delta] = CASE WHEN @Delta_Clear = 1 THEN NULL ELSE ISNULL(@Delta, [Delta]) END,
        [TrendDirection] = CASE WHEN @TrendDirection_Clear = 1 THEN NULL ELSE ISNULL(@TrendDirection, [TrendDirection]) END,
        [TrendSlope] = CASE WHEN @TrendSlope_Clear = 1 THEN NULL ELSE ISNULL(@TrendSlope, [TrendSlope]) END,
        [Confidence] = CASE WHEN @Confidence_Clear = 1 THEN NULL ELSE ISNULL(@Confidence, [Confidence]) END,
        [DataCompleteness] = CASE WHEN @DataCompleteness_Clear = 1 THEN NULL ELSE ISNULL(@DataCompleteness, [DataCompleteness]) END,
        [ComputedAt] = ISNULL(@ComputedAt, [ComputedAt]),
        [AsOfDate] = CASE WHEN @AsOfDate_Clear = 1 THEN NULL ELSE ISNULL(@AsOfDate, [AsOfDate]) END,
        [NextRecomputeAt] = CASE WHEN @NextRecomputeAt_Clear = 1 THEN NULL ELSE ISNULL(@NextRecomputeAt, [NextRecomputeAt]) END,
        [IsStale] = ISNULL(@IsStale, [IsStale]),
        [ExplanationSummary] = CASE WHEN @ExplanationSummary_Clear = 1 THEN NULL ELSE ISNULL(@ExplanationSummary, [ExplanationSummary]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwScores] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwScores]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateScore] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Score table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateScore]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateScore];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateScore
ON [${flyway:defaultSchema}].[Score]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Score]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[Score] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Sonar: Scores */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateScore] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Sonar: Scores */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Scores
-- Item: spDeleteScore
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Score
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteScore]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteScore];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteScore]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[Score]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteScore] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Sonar: Scores */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteScore] TO [cdp_Developer], [cdp_Integration];

/* SQL text to delete unneeded entity fields (3 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='52BA9A19-C7FF-47EA-AFFD-A398BB8AD3B2,1F1CBA7E-F548-420E-9B71-30891E454C42,32F2A760-5BFC-4AF6-BB18-11EF10DD254C';

/* SQL text to update existing entity fields from schema (3 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='52BA9A19-C7FF-47EA-AFFD-A398BB8AD3B2,1F1CBA7E-F548-420E-9B71-30891E454C42,32F2A760-5BFC-4AF6-BB18-11EF10DD254C';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

