-- =============================================================================
-- V202608031000__v0.5.x_Intervention_Proposal_Metadata.sql
-- =============================================================================
-- CODEGEN OUTPUT (auto-generated by `mj codegen`; do NOT hand-edit)
--
-- Folded in per the bizapps migration convention (see SECTION 5 of
-- V202606121005__v0.1.x_Initial_Schema.sql), the same way V202608011800 did it for the four
-- intervention-layer entities. Regenerate via `mj codegen`; do not edit here.
--
-- WHY THIS EXISTS: V202608021000 CREATED the InterventionProposal table but never registered it
-- with MJ. `mj app install` runs migrations ONLY, so on a fresh install the table existed with no
-- Entity/EntityField rows, no vwInterventionProposals view and no spCreate/spUpdate/spDelete
-- procedures. The entity layer had nothing to call, which means the Outreach approval tab — the
-- whole point of the draft-outreach slice — could not read or write a single proposal.
--
-- It worked on developer machines only because each of us had run `mj codegen` locally, which
-- quietly wrote that metadata into our own dev DBs. That is precisely the trap V202608011800
-- documents for the intervention-layer entities; this is the same gap, one entity later.
--
-- SCOPE: extracted from the CodeGen run that produced this metadata, restricted to the
-- Intervention Proposals sections. The same run also re-emitted vwInterventionOutcomes and the
-- Outcome CRUD procedures, which are deliberately EXCLUDED: V202608011800 already owns those, and
-- it records an intentional gap in them (the denormalized InterventionOutcome.Assignment display
-- column). Re-applying codegen's version here would silently overwrite that decision.
--
-- REPLAY BEHAVIOUR — measured, not assumed. This is NOT idempotent, and neither is V202608011800:
-- both emit unguarded `ALTER TABLE ... ADD [__mj_CreatedAt]/[__mj_UpdatedAt]` and unguarded
-- EntityFieldValue inserts, because CodeGen assumes it runs once against the table the previous
-- migration created WITHOUT audit columns. Replaying this file against a database that already has
-- them fails 5 of its 20 batches ("Column name '__mj_CreatedAt' ... specified more than once",
-- "Violation of PRIMARY KEY 'PK_EntityFieldValue_1'"). The view and procedures ARE guarded
-- (IF OBJECT_ID ... DROP), as are the Entity/Permission/Relationship rows (IF NOT EXISTS).
--
-- What that means in practice: on a fresh `mj app install` this is correct, because V202608021000
-- created the table bare. On a DEVELOPER machine whose metadata came from a local `mj codegen`
-- rather than from this chain, `mj migrate` will hit those failures — the same property the
-- intervention-layer metadata migration already has, so the existing handling applies.
-- =============================================================================

/* SQL generated to create new entity MJ_BizApps_Sonar: Intervention Proposals */

      INSERT INTO [${mjSchema}].[Entity] (
         [ID],
         [Name],
         [DisplayName],
         [Description],
         [NameSuffix],
         [BaseTable],
         [BaseView],
         [SchemaName],
         [IncludeInAPI],
         [AllowUserSearchAPI],
         [AllowCaching]
         , [TrackRecordChanges]
         , [AuditRecordAccess]
         , [AuditViewRuns]
         , [AllowAllRowsAPI]
         , [AllowCreateAPI]
         , [AllowUpdateAPI]
         , [AllowDeleteAPI]
         , [UserViewMaxRows]
         , [__mj_CreatedAt]
         , [__mj_UpdatedAt]
      )
      VALUES (
         '4dbe953d-52cc-4515-91d2-45c522c0991c',
         'MJ_BizApps_Sonar: Intervention Proposals',
         'Intervention Proposals',
         'A concrete per-member action a play prepared for human review (e.g. a drafted outreach email) — proposal type + payload are data, so new play types need no schema change.',
         NULL,
         'InterventionProposal',
         'vwInterventionProposals',
         '${flyway:defaultSchema}',
         1,
         1,
         0
         , 1
         , 0
         , 0
         , 0
         , 1
         , 1
         , 1
         , 1000
         , GETUTCDATE()
         , GETUTCDATE()
      );

/* SQL generated to add new entity MJ_BizApps_Sonar: Intervention Proposals to application ID: '4F9477FB-BC8B-4CA9-A4FE-C0FB45496285' */
INSERT INTO [${mjSchema}].[ApplicationEntity]
                                       ([ApplicationID], [EntityID], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                       ('4F9477FB-BC8B-4CA9-A4FE-C0FB45496285', '4dbe953d-52cc-4515-91d2-45c522c0991c', (SELECT COALESCE(MAX([Sequence]),0)+1 FROM [${mjSchema}].[ApplicationEntity] WHERE [ApplicationID] = '4F9477FB-BC8B-4CA9-A4FE-C0FB45496285'), GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity MJ_BizApps_Sonar: Intervention Proposals for role UI */
INSERT INTO [${mjSchema}].[EntityPermission]
                                                   ([EntityID], [RoleID], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                                   ('4dbe953d-52cc-4515-91d2-45c522c0991c', 'E0AFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 0, 0, 0, GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity MJ_BizApps_Sonar: Intervention Proposals for role Developer */
INSERT INTO [${mjSchema}].[EntityPermission]
                                                   ([EntityID], [RoleID], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                                   ('4dbe953d-52cc-4515-91d2-45c522c0991c', 'DEAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity MJ_BizApps_Sonar: Intervention Proposals for role Integration */
INSERT INTO [${mjSchema}].[EntityPermission]
                                                   ([EntityID], [RoleID], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                                   ('4dbe953d-52cc-4515-91d2-45c522c0991c', 'DFAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE());

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to add special date field __mj_CreatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
ALTER TABLE [${flyway:defaultSchema}].[InterventionProposal] ADD [__mj_CreatedAt] DATETIMEOFFSET NULL;
GO

/* SQL text to add special date field __mj_CreatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
UPDATE [${flyway:defaultSchema}].[InterventionProposal] SET [__mj_CreatedAt] = GETUTCDATE() WHERE [__mj_CreatedAt] IS NULL;
GO

/* SQL text to add special date field __mj_CreatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
ALTER TABLE [${flyway:defaultSchema}].[InterventionProposal] ALTER COLUMN [__mj_CreatedAt] DATETIMEOFFSET NOT NULL;
GO

/* SQL text to add special date field __mj_CreatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
ALTER TABLE [${flyway:defaultSchema}].[InterventionProposal] ADD CONSTRAINT [DF___mj_BizAppsSonar_InterventionProposal___mj_CreatedAt] DEFAULT GETUTCDATE() FOR [__mj_CreatedAt];
GO

/* SQL text to add special date field __mj_UpdatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
ALTER TABLE [${flyway:defaultSchema}].[InterventionProposal] ADD [__mj_UpdatedAt] DATETIMEOFFSET NULL;
GO

/* SQL text to add special date field __mj_UpdatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
UPDATE [${flyway:defaultSchema}].[InterventionProposal] SET [__mj_UpdatedAt] = GETUTCDATE() WHERE [__mj_UpdatedAt] IS NULL;
GO

/* SQL text to add special date field __mj_UpdatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
ALTER TABLE [${flyway:defaultSchema}].[InterventionProposal] ALTER COLUMN [__mj_UpdatedAt] DATETIMEOFFSET NOT NULL;
GO

/* SQL text to add special date field __mj_UpdatedAt to entity ${flyway:defaultSchema}.InterventionProposal */
ALTER TABLE [${flyway:defaultSchema}].[InterventionProposal] ADD CONSTRAINT [DF___mj_BizAppsSonar_InterventionProposal___mj_UpdatedAt] DEFAULT GETUTCDATE() FOR [__mj_UpdatedAt];
GO

/* SQL text to insert 13 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'd28cbe22-c8f9-4723-8788-75efa0fccb9a' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'ID')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'd28cbe22-c8f9-4723-8788-75efa0fccb9a',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100001,
            'ID',
            'ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            'newsequentialid()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            1,
            0,
            0,
            1,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '826f2a6b-30a5-4da3-ae21-1d8ea996695f' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'InterventionID')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '826f2a6b-30a5-4da3-ae21-1d8ea996695f',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100002,
            'InterventionID',
            'Intervention ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            '2140617E-A375-41F2-8DD5-346E7555EC04',
            'ID',
            0,
            0,
            1,
            0,
            0,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'af4e204f-f8c9-4d76-b346-141d04786c4a' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'AnchorRecordID')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'af4e204f-f8c9-4d76-b346-141d04786c4a',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100003,
            'AnchorRecordID',
            'Anchor Record ID',
            'Canonical id of the anchor record this proposal is for (matches Score.AnchorRecordID).',
            'nvarchar',
            900,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '42302142-624e-49a8-ad56-bb9ad09bdd28' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'AnchorName')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '42302142-624e-49a8-ad56-bb9ad09bdd28',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100004,
            'AnchorName',
            'Anchor Name',
            'Display name of the member at draft time (denormalized so the review queue never re-resolves anchors).',
            'nvarchar',
            600,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'c929cdb0-ed6a-49ce-b4b7-fed24a133007' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'ProposalType')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'c929cdb0-ed6a-49ce-b4b7-fed24a133007',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100005,
            'ProposalType',
            'Proposal Type',
            'What kind of action is proposed (e.g. EmailDraft). Determines how PayloadJSON is shaped and rendered; an open set — new plays add new types.',
            'nvarchar',
            60,
            0,
            0,
            0,
            'EmailDraft',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'ac151076-fe5d-4c66-bede-cc9c0bcb4d77' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'Rationale')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'ac151076-fe5d-4c66-bede-cc9c0bcb4d77',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100006,
            'Rationale',
            'Rationale',
            'One-line human-readable reason this member got this proposal (shown on the review queue card).',
            'nvarchar',
            2000,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'b19ebe7e-1200-49c3-b3b1-df612ec0fa90' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'PayloadJSON')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'b19ebe7e-1200-49c3-b3b1-df612ec0fa90',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100007,
            'PayloadJSON',
            'Payload JSON',
            'The proposal content, shaped per ProposalType (EmailDraft: {subject, body, recipientEmail}).',
            'nvarchar',
            -1,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '7237e1e6-51c5-45d6-af91-312b6a1da97e' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'GroundingJSON')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '7237e1e6-51c5-45d6-af91-312b6a1da97e',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100008,
            'GroundingJSON',
            'Grounding JSON',
            'The score facts the proposal was grounded in ({score, bandName, delta, dominantCause, factors[]}) — the audit trail for "why this member".',
            'nvarchar',
            -1,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '7e993438-3bf0-4585-bb13-2220c61eb20a' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'Status')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '7e993438-3bf0-4585-bb13-2220c61eb20a',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100009,
            'Status',
            'Status',
            'Review lifecycle: Proposed (awaiting review), Approved, Rejected, or Executed (carried out — for the PoC, a simulated send).',
            'nvarchar',
            32,
            0,
            0,
            0,
            'Proposed',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '1e1fb41e-1ed4-4852-bae7-2f92028d050b' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'ReviewedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '1e1fb41e-1ed4-4852-bae7-2f92028d050b',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100010,
            'ReviewedAt',
            'Reviewed At',
            'When a human approved or rejected the proposal.',
            'datetime2',
            8,
            27,
            7,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '987cf28e-3f79-4cb4-9739-b8b9de6e9286' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = 'ExecutedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '987cf28e-3f79-4cb4-9739-b8b9de6e9286',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100011,
            'ExecutedAt',
            'Executed At',
            'When the approved proposal was executed (PoC: the simulated send).',
            'datetime2',
            8,
            27,
            7,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'c534a487-0ae2-4788-a2a1-389b0c6b1b04' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = '__mj_CreatedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'c534a487-0ae2-4788-a2a1-389b0c6b1b04',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100012,
            '__mj_CreatedAt',
            'Created At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'b1d87d5e-b6be-4290-b57f-b19db1553e7b' OR (EntityID = '4DBE953D-52CC-4515-91D2-45C522C0991C' AND Name = '__mj_UpdatedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'b1d87d5e-b6be-4290-b57f-b19db1553e7b',
            '4DBE953D-52CC-4515-91D2-45C522C0991C', -- Entity: MJ_BizApps_Sonar: Intervention Proposals
            100013,
            '__mj_UpdatedAt',
            'Updated At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to insert entity field value with ID e0dd19b0-2b2a-42b5-a52f-b6ae254ccdc3 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('e0dd19b0-2b2a-42b5-a52f-b6ae254ccdc3', '7E993438-3BF0-4585-BB13-2220C61EB20A', 1, 'Approved', 'Approved', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID e5ab0371-612d-47ee-a37f-182c132333a4 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('e5ab0371-612d-47ee-a37f-182c132333a4', '7E993438-3BF0-4585-BB13-2220C61EB20A', 2, 'Executed', 'Executed', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID ee033a8f-159c-43b9-9e8d-3834710a0db2 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('ee033a8f-159c-43b9-9e8d-3834710a0db2', '7E993438-3BF0-4585-BB13-2220C61EB20A', 3, 'Proposed', 'Proposed', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID 3b9d468b-279c-487a-84d0-d51d09cf85db */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('3b9d468b-279c-487a-84d0-d51d09cf85db', '7E993438-3BF0-4585-BB13-2220C61EB20A', 4, 'Rejected', 'Rejected', GETUTCDATE(), GETUTCDATE());

/* SQL text to update ValueListType for entity field ID 7E993438-3BF0-4585-BB13-2220C61EB20A */
UPDATE [${mjSchema}].[EntityField] SET ValueListType='List' WHERE ID='7E993438-3BF0-4585-BB13-2220C61EB20A';


/* Create Entity Relationship: MJ_BizApps_Sonar: Interventions -> MJ_BizApps_Sonar: Intervention Proposals (One To Many via InterventionID) */
   IF NOT EXISTS (
      SELECT 1 FROM [${mjSchema}].[EntityRelationship] WHERE [ID] = '537aaa0a-83fb-42d2-922e-1eddf458cf05'
   )
   BEGIN
      INSERT INTO [${mjSchema}].[EntityRelationship] ([ID], [EntityID], [RelatedEntityID], [RelatedEntityJoinField], [Type], [BundleInAPI], [DisplayInForm], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt])
                    VALUES ('537aaa0a-83fb-42d2-922e-1eddf458cf05', '2140617E-A375-41F2-8DD5-346E7555EC04', '4DBE953D-52CC-4515-91D2-45C522C0991C', 'InterventionID', 'One To Many', 1, 1, 2, GETUTCDATE(), GETUTCDATE())
   END;

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to update entity field related entity name field map for entity field ID 49DE05E4-534C-469A-9F0F-CA4C2F27EC30 */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='49DE05E4-534C-469A-9F0F-CA4C2F27EC30', @RelatedEntityNameFieldMap='Assignment';

/* Index for Foreign Keys for InterventionProposal */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Intervention Proposals
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key InterventionID in table InterventionProposal
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_InterventionProposal_InterventionID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[InterventionProposal]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_InterventionProposal_InterventionID ON [${flyway:defaultSchema}].[InterventionProposal] ([InterventionID]);

/* SQL text to update entity field related entity name field map for entity field ID 826F2A6B-30A5-4DA3-AE21-1D8EA996695F */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='826F2A6B-30A5-4DA3-AE21-1D8EA996695F', @RelatedEntityNameFieldMap='Intervention';

/* Base View SQL for MJ_BizApps_Sonar: Intervention Proposals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Intervention Proposals
-- Item: vwInterventionProposals
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Sonar: Intervention Proposals
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  InterventionProposal
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwInterventionProposals]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwInterventionProposals];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwInterventionProposals]
AS
SELECT
    i.*,
    mjBizAppsSonarIntervention_InterventionID.[Name] AS [Intervention]
FROM
    [${flyway:defaultSchema}].[InterventionProposal] AS i
INNER JOIN
    [${flyway:defaultSchema}].[Intervention] AS mjBizAppsSonarIntervention_InterventionID
  ON
    [i].[InterventionID] = mjBizAppsSonarIntervention_InterventionID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwInterventionProposals] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Sonar: Intervention Proposals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Intervention Proposals
-- Item: Permissions for vwInterventionProposals
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwInterventionProposals] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Sonar: Intervention Proposals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Intervention Proposals
-- Item: spCreateInterventionProposal
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR InterventionProposal
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateInterventionProposal]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateInterventionProposal];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateInterventionProposal]
    @ID uniqueidentifier = NULL,
    @InterventionID uniqueidentifier,
    @AnchorRecordID nvarchar(450),
    @AnchorName_Clear bit = 0,
    @AnchorName nvarchar(300) = NULL,
    @ProposalType nvarchar(30) = NULL,
    @Rationale_Clear bit = 0,
    @Rationale nvarchar(1000) = NULL,
    @PayloadJSON_Clear bit = 0,
    @PayloadJSON nvarchar(MAX) = NULL,
    @GroundingJSON_Clear bit = 0,
    @GroundingJSON nvarchar(MAX) = NULL,
    @Status nvarchar(16) = NULL,
    @ReviewedAt_Clear bit = 0,
    @ReviewedAt datetime2 = NULL,
    @ExecutedAt_Clear bit = 0,
    @ExecutedAt datetime2 = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[InterventionProposal]
            (
                [ID],
                [InterventionID],
                [AnchorRecordID],
                [AnchorName],
                [ProposalType],
                [Rationale],
                [PayloadJSON],
                [GroundingJSON],
                [Status],
                [ReviewedAt],
                [ExecutedAt]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @InterventionID,
                @AnchorRecordID,
                CASE WHEN @AnchorName_Clear = 1 THEN NULL ELSE ISNULL(@AnchorName, NULL) END,
                ISNULL(@ProposalType, 'EmailDraft'),
                CASE WHEN @Rationale_Clear = 1 THEN NULL ELSE ISNULL(@Rationale, NULL) END,
                CASE WHEN @PayloadJSON_Clear = 1 THEN NULL ELSE ISNULL(@PayloadJSON, NULL) END,
                CASE WHEN @GroundingJSON_Clear = 1 THEN NULL ELSE ISNULL(@GroundingJSON, NULL) END,
                ISNULL(@Status, 'Proposed'),
                CASE WHEN @ReviewedAt_Clear = 1 THEN NULL ELSE ISNULL(@ReviewedAt, NULL) END,
                CASE WHEN @ExecutedAt_Clear = 1 THEN NULL ELSE ISNULL(@ExecutedAt, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[InterventionProposal]
            (
                [InterventionID],
                [AnchorRecordID],
                [AnchorName],
                [ProposalType],
                [Rationale],
                [PayloadJSON],
                [GroundingJSON],
                [Status],
                [ReviewedAt],
                [ExecutedAt]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @InterventionID,
                @AnchorRecordID,
                CASE WHEN @AnchorName_Clear = 1 THEN NULL ELSE ISNULL(@AnchorName, NULL) END,
                ISNULL(@ProposalType, 'EmailDraft'),
                CASE WHEN @Rationale_Clear = 1 THEN NULL ELSE ISNULL(@Rationale, NULL) END,
                CASE WHEN @PayloadJSON_Clear = 1 THEN NULL ELSE ISNULL(@PayloadJSON, NULL) END,
                CASE WHEN @GroundingJSON_Clear = 1 THEN NULL ELSE ISNULL(@GroundingJSON, NULL) END,
                ISNULL(@Status, 'Proposed'),
                CASE WHEN @ReviewedAt_Clear = 1 THEN NULL ELSE ISNULL(@ReviewedAt, NULL) END,
                CASE WHEN @ExecutedAt_Clear = 1 THEN NULL ELSE ISNULL(@ExecutedAt, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwInterventionProposals] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateInterventionProposal] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Sonar: Intervention Proposals */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateInterventionProposal] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Sonar: Intervention Proposals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Intervention Proposals
-- Item: spUpdateInterventionProposal
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR InterventionProposal
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateInterventionProposal]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateInterventionProposal];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateInterventionProposal]
    @ID uniqueidentifier,
    @InterventionID uniqueidentifier = NULL,
    @AnchorRecordID nvarchar(450) = NULL,
    @AnchorName_Clear bit = 0,
    @AnchorName nvarchar(300) = NULL,
    @ProposalType nvarchar(30) = NULL,
    @Rationale_Clear bit = 0,
    @Rationale nvarchar(1000) = NULL,
    @PayloadJSON_Clear bit = 0,
    @PayloadJSON nvarchar(MAX) = NULL,
    @GroundingJSON_Clear bit = 0,
    @GroundingJSON nvarchar(MAX) = NULL,
    @Status nvarchar(16) = NULL,
    @ReviewedAt_Clear bit = 0,
    @ReviewedAt datetime2 = NULL,
    @ExecutedAt_Clear bit = 0,
    @ExecutedAt datetime2 = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[InterventionProposal]
    SET
        [InterventionID] = ISNULL(@InterventionID, [InterventionID]),
        [AnchorRecordID] = ISNULL(@AnchorRecordID, [AnchorRecordID]),
        [AnchorName] = CASE WHEN @AnchorName_Clear = 1 THEN NULL ELSE ISNULL(@AnchorName, [AnchorName]) END,
        [ProposalType] = ISNULL(@ProposalType, [ProposalType]),
        [Rationale] = CASE WHEN @Rationale_Clear = 1 THEN NULL ELSE ISNULL(@Rationale, [Rationale]) END,
        [PayloadJSON] = CASE WHEN @PayloadJSON_Clear = 1 THEN NULL ELSE ISNULL(@PayloadJSON, [PayloadJSON]) END,
        [GroundingJSON] = CASE WHEN @GroundingJSON_Clear = 1 THEN NULL ELSE ISNULL(@GroundingJSON, [GroundingJSON]) END,
        [Status] = ISNULL(@Status, [Status]),
        [ReviewedAt] = CASE WHEN @ReviewedAt_Clear = 1 THEN NULL ELSE ISNULL(@ReviewedAt, [ReviewedAt]) END,
        [ExecutedAt] = CASE WHEN @ExecutedAt_Clear = 1 THEN NULL ELSE ISNULL(@ExecutedAt, [ExecutedAt]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwInterventionProposals] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwInterventionProposals]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateInterventionProposal] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the InterventionProposal table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateInterventionProposal]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateInterventionProposal];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateInterventionProposal
ON [${flyway:defaultSchema}].[InterventionProposal]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[InterventionProposal]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[InterventionProposal] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Sonar: Intervention Proposals */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateInterventionProposal] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Sonar: Intervention Proposals */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Intervention Proposals
-- Item: spDeleteInterventionProposal
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR InterventionProposal
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteInterventionProposal]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteInterventionProposal];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteInterventionProposal]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[InterventionProposal]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteInterventionProposal] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Sonar: Intervention Proposals */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteInterventionProposal] TO [cdp_Developer], [cdp_Integration];
