-- Add Factor.DateField — the related-entity activity-date column a windowed factor filters on
-- (e.g. RegistrationDate, the "when did it happen" column). Until now the engine read this from
-- TimeWindow.AnchorDateField, which is a latent bug: TimeWindow must stay reusable/entity-agnostic,
-- and a Rolling window with AnchorDateField=null silently counted everything. This column moves the
-- "which date column" decision onto the Factor (where the source entity is known), freeing
-- TimeWindow.AnchorDateField to mean what §5.2 intended: the ANCHOR-side boundary date for
-- SinceEvent / RenewalRelative windows.
--
-- Migration only adds the column; the engine rewiring (FactorCompiler/factorSql read DateField for the
-- related date; wire SinceEvent/RenewalRelative) and the factor-builder DateField picker follow in code.
ALTER TABLE ${flyway:defaultSchema}.Factor
    ADD DateField NVARCHAR(200) NULL;
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'The date column on the factor''s related (source) entity that a time window filters on — the "when did it happen" column (e.g. RegistrationDate). Used by Rolling/Calendar/SinceEvent windows; null = no date filter (count everything in scope).',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'Factor',
    @level2type = N'COLUMN', @level2name = N'DateField';
GO

-- ============================================================================
-- CodeGen output — regenerated Factor view / CRUD procs / FK indexes / entity-field
-- metadata for the new DateField column. Generated by 'mj codegen' and appended per the
-- migration convention (see the Initial Schema migration's embedded codegen section).
-- ============================================================================

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to insert new entity field */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '33b91f2b-bad3-487c-8b81-0ded8b0db8b2' OR (EntityID = '01BC22BE-E8C3-4C17-912B-FC2AF1E2DC03' AND Name = 'DateField')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '33b91f2b-bad3-487c-8b81-0ded8b0db8b2',
            '01BC22BE-E8C3-4C17-912B-FC2AF1E2DC03', -- Entity: MJ_BizApps_Sonar: Factors
            100073,
            'DateField',
            'Date Field',
            'The date column on the factor''s related (source) entity that a time window filters on — the "when did it happen" column (e.g. RegistrationDate). Used by Rolling/Calendar/SinceEvent windows; null = no date filter (count everything in scope).',
            'nvarchar',
            400,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

/* Index for Foreign Keys for Factor */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Factors
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ScoreModelID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_ScoreModelID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_ScoreModelID ON [${flyway:defaultSchema}].[Factor] ([ScoreModelID]);

-- Index for foreign key AnchorEntityID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_AnchorEntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_AnchorEntityID ON [${flyway:defaultSchema}].[Factor] ([AnchorEntityID]);

-- Index for foreign key SourceRelatedEntityID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_SourceRelatedEntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_SourceRelatedEntityID ON [${flyway:defaultSchema}].[Factor] ([SourceRelatedEntityID]);

-- Index for foreign key SourceEntityID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_SourceEntityID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_SourceEntityID ON [${flyway:defaultSchema}].[Factor] ([SourceEntityID]);

-- Index for foreign key TimeWindowID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_TimeWindowID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_TimeWindowID ON [${flyway:defaultSchema}].[Factor] ([TimeWindowID]);

-- Index for foreign key ActionID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_ActionID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_ActionID ON [${flyway:defaultSchema}].[Factor] ([ActionID]);

-- Index for foreign key SourceScoreModelID in table Factor
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Factor_SourceScoreModelID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Factor]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Factor_SourceScoreModelID ON [${flyway:defaultSchema}].[Factor] ([SourceScoreModelID]);

/* Base View SQL for MJ_BizApps_Sonar: Factors */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Factors
-- Item: vwFactors
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Sonar: Factors
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  Factor
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwFactors]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwFactors];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwFactors]
AS
SELECT
    f.*,
    mjBizAppsSonarScoreModel_ScoreModelID.[Name] AS [ScoreModel],
    MJEntity_AnchorEntityID.[Name] AS [AnchorEntity],
    MJEntity_SourceEntityID.[Name] AS [SourceEntity],
    mjBizAppsSonarTimeWindow_TimeWindowID.[Name] AS [TimeWindow],
    MJAction_ActionID.[Name] AS [Action],
    mjBizAppsSonarScoreModel_SourceScoreModelID.[Name] AS [SourceScoreModel]
FROM
    [${flyway:defaultSchema}].[Factor] AS f
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ScoreModel] AS mjBizAppsSonarScoreModel_ScoreModelID
  ON
    [f].[ScoreModelID] = mjBizAppsSonarScoreModel_ScoreModelID.[ID]
INNER JOIN
    [${mjSchema}].[Entity] AS MJEntity_AnchorEntityID
  ON
    [f].[AnchorEntityID] = MJEntity_AnchorEntityID.[ID]
LEFT OUTER JOIN
    [${mjSchema}].[Entity] AS MJEntity_SourceEntityID
  ON
    [f].[SourceEntityID] = MJEntity_SourceEntityID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[TimeWindow] AS mjBizAppsSonarTimeWindow_TimeWindowID
  ON
    [f].[TimeWindowID] = mjBizAppsSonarTimeWindow_TimeWindowID.[ID]
LEFT OUTER JOIN
    [${mjSchema}].[Action] AS MJAction_ActionID
  ON
    [f].[ActionID] = MJAction_ActionID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[ScoreModel] AS mjBizAppsSonarScoreModel_SourceScoreModelID
  ON
    [f].[SourceScoreModelID] = mjBizAppsSonarScoreModel_SourceScoreModelID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwFactors] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Sonar: Factors */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Factors
-- Item: Permissions for vwFactors
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwFactors] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Sonar: Factors */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Factors
-- Item: spCreateFactor
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Factor
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateFactor]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateFactor];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateFactor]
    @ID uniqueidentifier = NULL,
    @Name nvarchar(200),
    @Slug nvarchar(100),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @ScoreModelID_Clear bit = 0,
    @ScoreModelID uniqueidentifier = NULL,
    @AnchorEntityID uniqueidentifier,
    @FactorType nvarchar(20),
    @SourceRelatedEntityID_Clear bit = 0,
    @SourceRelatedEntityID uniqueidentifier = NULL,
    @SourceEntityID_Clear bit = 0,
    @SourceEntityID uniqueidentifier = NULL,
    @FilterExpression_Clear bit = 0,
    @FilterExpression nvarchar(MAX) = NULL,
    @Aggregation_Clear bit = 0,
    @Aggregation nvarchar(20) = NULL,
    @AggregateFieldName_Clear bit = 0,
    @AggregateFieldName nvarchar(200) = NULL,
    @TimeWindowID_Clear bit = 0,
    @TimeWindowID uniqueidentifier = NULL,
    @RecencyDecayHalfLifeDays_Clear bit = 0,
    @RecencyDecayHalfLifeDays int = NULL,
    @ActionID_Clear bit = 0,
    @ActionID uniqueidentifier = NULL,
    @ActionParamsJSON_Clear bit = 0,
    @ActionParamsJSON nvarchar(MAX) = NULL,
    @ExecutionMode_Clear bit = 0,
    @ExecutionMode nvarchar(12) = NULL,
    @IsExpensive bit = NULL,
    @MaxConcurrency_Clear bit = 0,
    @MaxConcurrency int = NULL,
    @RateLimitPerMinute_Clear bit = 0,
    @RateLimitPerMinute int = NULL,
    @CacheTTLSeconds_Clear bit = 0,
    @CacheTTLSeconds int = NULL,
    @SourceScoreModelID_Clear bit = 0,
    @SourceScoreModelID uniqueidentifier = NULL,
    @RawDataType_Clear bit = 0,
    @RawDataType nvarchar(12) = NULL,
    @NormalizationMethod_Clear bit = 0,
    @NormalizationMethod nvarchar(20) = NULL,
    @NormalizationParamsJSON_Clear bit = 0,
    @NormalizationParamsJSON nvarchar(MAX) = NULL,
    @OutputMin_Clear bit = 0,
    @OutputMin decimal(9, 4) = NULL,
    @OutputMax_Clear bit = 0,
    @OutputMax decimal(9, 4) = NULL,
    @HigherIsBetter bit = NULL,
    @PromotionState_Clear bit = 0,
    @PromotionState nvarchar(20) = NULL,
    @LastValidatedAt_Clear bit = 0,
    @LastValidatedAt datetime2 = NULL,
    @CreatedByAgent_Clear bit = 0,
    @CreatedByAgent nvarchar(60) = NULL,
    @DateField_Clear bit = 0,
    @DateField nvarchar(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Factor]
            (
                [ID],
                [Name],
                [Slug],
                [Description],
                [ScoreModelID],
                [AnchorEntityID],
                [FactorType],
                [SourceRelatedEntityID],
                [SourceEntityID],
                [FilterExpression],
                [Aggregation],
                [AggregateFieldName],
                [TimeWindowID],
                [RecencyDecayHalfLifeDays],
                [ActionID],
                [ActionParamsJSON],
                [ExecutionMode],
                [IsExpensive],
                [MaxConcurrency],
                [RateLimitPerMinute],
                [CacheTTLSeconds],
                [SourceScoreModelID],
                [RawDataType],
                [NormalizationMethod],
                [NormalizationParamsJSON],
                [OutputMin],
                [OutputMax],
                [HigherIsBetter],
                [PromotionState],
                [LastValidatedAt],
                [CreatedByAgent],
                [DateField]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Name,
                @Slug,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                CASE WHEN @ScoreModelID_Clear = 1 THEN NULL ELSE ISNULL(@ScoreModelID, NULL) END,
                @AnchorEntityID,
                @FactorType,
                CASE WHEN @SourceRelatedEntityID_Clear = 1 THEN NULL ELSE ISNULL(@SourceRelatedEntityID, NULL) END,
                CASE WHEN @SourceEntityID_Clear = 1 THEN NULL ELSE ISNULL(@SourceEntityID, NULL) END,
                CASE WHEN @FilterExpression_Clear = 1 THEN NULL ELSE ISNULL(@FilterExpression, NULL) END,
                CASE WHEN @Aggregation_Clear = 1 THEN NULL ELSE ISNULL(@Aggregation, NULL) END,
                CASE WHEN @AggregateFieldName_Clear = 1 THEN NULL ELSE ISNULL(@AggregateFieldName, NULL) END,
                CASE WHEN @TimeWindowID_Clear = 1 THEN NULL ELSE ISNULL(@TimeWindowID, NULL) END,
                CASE WHEN @RecencyDecayHalfLifeDays_Clear = 1 THEN NULL ELSE ISNULL(@RecencyDecayHalfLifeDays, NULL) END,
                CASE WHEN @ActionID_Clear = 1 THEN NULL ELSE ISNULL(@ActionID, NULL) END,
                CASE WHEN @ActionParamsJSON_Clear = 1 THEN NULL ELSE ISNULL(@ActionParamsJSON, NULL) END,
                CASE WHEN @ExecutionMode_Clear = 1 THEN NULL ELSE ISNULL(@ExecutionMode, NULL) END,
                ISNULL(@IsExpensive, 0),
                CASE WHEN @MaxConcurrency_Clear = 1 THEN NULL ELSE ISNULL(@MaxConcurrency, NULL) END,
                CASE WHEN @RateLimitPerMinute_Clear = 1 THEN NULL ELSE ISNULL(@RateLimitPerMinute, NULL) END,
                CASE WHEN @CacheTTLSeconds_Clear = 1 THEN NULL ELSE ISNULL(@CacheTTLSeconds, NULL) END,
                CASE WHEN @SourceScoreModelID_Clear = 1 THEN NULL ELSE ISNULL(@SourceScoreModelID, NULL) END,
                CASE WHEN @RawDataType_Clear = 1 THEN NULL ELSE ISNULL(@RawDataType, NULL) END,
                CASE WHEN @NormalizationMethod_Clear = 1 THEN NULL ELSE ISNULL(@NormalizationMethod, NULL) END,
                CASE WHEN @NormalizationParamsJSON_Clear = 1 THEN NULL ELSE ISNULL(@NormalizationParamsJSON, NULL) END,
                CASE WHEN @OutputMin_Clear = 1 THEN NULL ELSE ISNULL(@OutputMin, NULL) END,
                CASE WHEN @OutputMax_Clear = 1 THEN NULL ELSE ISNULL(@OutputMax, NULL) END,
                ISNULL(@HigherIsBetter, 1),
                CASE WHEN @PromotionState_Clear = 1 THEN NULL ELSE ISNULL(@PromotionState, NULL) END,
                CASE WHEN @LastValidatedAt_Clear = 1 THEN NULL ELSE ISNULL(@LastValidatedAt, NULL) END,
                CASE WHEN @CreatedByAgent_Clear = 1 THEN NULL ELSE ISNULL(@CreatedByAgent, NULL) END,
                CASE WHEN @DateField_Clear = 1 THEN NULL ELSE ISNULL(@DateField, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Factor]
            (
                [Name],
                [Slug],
                [Description],
                [ScoreModelID],
                [AnchorEntityID],
                [FactorType],
                [SourceRelatedEntityID],
                [SourceEntityID],
                [FilterExpression],
                [Aggregation],
                [AggregateFieldName],
                [TimeWindowID],
                [RecencyDecayHalfLifeDays],
                [ActionID],
                [ActionParamsJSON],
                [ExecutionMode],
                [IsExpensive],
                [MaxConcurrency],
                [RateLimitPerMinute],
                [CacheTTLSeconds],
                [SourceScoreModelID],
                [RawDataType],
                [NormalizationMethod],
                [NormalizationParamsJSON],
                [OutputMin],
                [OutputMax],
                [HigherIsBetter],
                [PromotionState],
                [LastValidatedAt],
                [CreatedByAgent],
                [DateField]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Name,
                @Slug,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                CASE WHEN @ScoreModelID_Clear = 1 THEN NULL ELSE ISNULL(@ScoreModelID, NULL) END,
                @AnchorEntityID,
                @FactorType,
                CASE WHEN @SourceRelatedEntityID_Clear = 1 THEN NULL ELSE ISNULL(@SourceRelatedEntityID, NULL) END,
                CASE WHEN @SourceEntityID_Clear = 1 THEN NULL ELSE ISNULL(@SourceEntityID, NULL) END,
                CASE WHEN @FilterExpression_Clear = 1 THEN NULL ELSE ISNULL(@FilterExpression, NULL) END,
                CASE WHEN @Aggregation_Clear = 1 THEN NULL ELSE ISNULL(@Aggregation, NULL) END,
                CASE WHEN @AggregateFieldName_Clear = 1 THEN NULL ELSE ISNULL(@AggregateFieldName, NULL) END,
                CASE WHEN @TimeWindowID_Clear = 1 THEN NULL ELSE ISNULL(@TimeWindowID, NULL) END,
                CASE WHEN @RecencyDecayHalfLifeDays_Clear = 1 THEN NULL ELSE ISNULL(@RecencyDecayHalfLifeDays, NULL) END,
                CASE WHEN @ActionID_Clear = 1 THEN NULL ELSE ISNULL(@ActionID, NULL) END,
                CASE WHEN @ActionParamsJSON_Clear = 1 THEN NULL ELSE ISNULL(@ActionParamsJSON, NULL) END,
                CASE WHEN @ExecutionMode_Clear = 1 THEN NULL ELSE ISNULL(@ExecutionMode, NULL) END,
                ISNULL(@IsExpensive, 0),
                CASE WHEN @MaxConcurrency_Clear = 1 THEN NULL ELSE ISNULL(@MaxConcurrency, NULL) END,
                CASE WHEN @RateLimitPerMinute_Clear = 1 THEN NULL ELSE ISNULL(@RateLimitPerMinute, NULL) END,
                CASE WHEN @CacheTTLSeconds_Clear = 1 THEN NULL ELSE ISNULL(@CacheTTLSeconds, NULL) END,
                CASE WHEN @SourceScoreModelID_Clear = 1 THEN NULL ELSE ISNULL(@SourceScoreModelID, NULL) END,
                CASE WHEN @RawDataType_Clear = 1 THEN NULL ELSE ISNULL(@RawDataType, NULL) END,
                CASE WHEN @NormalizationMethod_Clear = 1 THEN NULL ELSE ISNULL(@NormalizationMethod, NULL) END,
                CASE WHEN @NormalizationParamsJSON_Clear = 1 THEN NULL ELSE ISNULL(@NormalizationParamsJSON, NULL) END,
                CASE WHEN @OutputMin_Clear = 1 THEN NULL ELSE ISNULL(@OutputMin, NULL) END,
                CASE WHEN @OutputMax_Clear = 1 THEN NULL ELSE ISNULL(@OutputMax, NULL) END,
                ISNULL(@HigherIsBetter, 1),
                CASE WHEN @PromotionState_Clear = 1 THEN NULL ELSE ISNULL(@PromotionState, NULL) END,
                CASE WHEN @LastValidatedAt_Clear = 1 THEN NULL ELSE ISNULL(@LastValidatedAt, NULL) END,
                CASE WHEN @CreatedByAgent_Clear = 1 THEN NULL ELSE ISNULL(@CreatedByAgent, NULL) END,
                CASE WHEN @DateField_Clear = 1 THEN NULL ELSE ISNULL(@DateField, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwFactors] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateFactor] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Sonar: Factors */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateFactor] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Sonar: Factors */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Factors
-- Item: spUpdateFactor
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Factor
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateFactor]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateFactor];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateFactor]
    @ID uniqueidentifier,
    @Name nvarchar(200) = NULL,
    @Slug nvarchar(100) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @ScoreModelID_Clear bit = 0,
    @ScoreModelID uniqueidentifier = NULL,
    @AnchorEntityID uniqueidentifier = NULL,
    @FactorType nvarchar(20) = NULL,
    @SourceRelatedEntityID_Clear bit = 0,
    @SourceRelatedEntityID uniqueidentifier = NULL,
    @SourceEntityID_Clear bit = 0,
    @SourceEntityID uniqueidentifier = NULL,
    @FilterExpression_Clear bit = 0,
    @FilterExpression nvarchar(MAX) = NULL,
    @Aggregation_Clear bit = 0,
    @Aggregation nvarchar(20) = NULL,
    @AggregateFieldName_Clear bit = 0,
    @AggregateFieldName nvarchar(200) = NULL,
    @TimeWindowID_Clear bit = 0,
    @TimeWindowID uniqueidentifier = NULL,
    @RecencyDecayHalfLifeDays_Clear bit = 0,
    @RecencyDecayHalfLifeDays int = NULL,
    @ActionID_Clear bit = 0,
    @ActionID uniqueidentifier = NULL,
    @ActionParamsJSON_Clear bit = 0,
    @ActionParamsJSON nvarchar(MAX) = NULL,
    @ExecutionMode_Clear bit = 0,
    @ExecutionMode nvarchar(12) = NULL,
    @IsExpensive bit = NULL,
    @MaxConcurrency_Clear bit = 0,
    @MaxConcurrency int = NULL,
    @RateLimitPerMinute_Clear bit = 0,
    @RateLimitPerMinute int = NULL,
    @CacheTTLSeconds_Clear bit = 0,
    @CacheTTLSeconds int = NULL,
    @SourceScoreModelID_Clear bit = 0,
    @SourceScoreModelID uniqueidentifier = NULL,
    @RawDataType_Clear bit = 0,
    @RawDataType nvarchar(12) = NULL,
    @NormalizationMethod_Clear bit = 0,
    @NormalizationMethod nvarchar(20) = NULL,
    @NormalizationParamsJSON_Clear bit = 0,
    @NormalizationParamsJSON nvarchar(MAX) = NULL,
    @OutputMin_Clear bit = 0,
    @OutputMin decimal(9, 4) = NULL,
    @OutputMax_Clear bit = 0,
    @OutputMax decimal(9, 4) = NULL,
    @HigherIsBetter bit = NULL,
    @PromotionState_Clear bit = 0,
    @PromotionState nvarchar(20) = NULL,
    @LastValidatedAt_Clear bit = 0,
    @LastValidatedAt datetime2 = NULL,
    @CreatedByAgent_Clear bit = 0,
    @CreatedByAgent nvarchar(60) = NULL,
    @DateField_Clear bit = 0,
    @DateField nvarchar(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Factor]
    SET
        [Name] = ISNULL(@Name, [Name]),
        [Slug] = ISNULL(@Slug, [Slug]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [ScoreModelID] = CASE WHEN @ScoreModelID_Clear = 1 THEN NULL ELSE ISNULL(@ScoreModelID, [ScoreModelID]) END,
        [AnchorEntityID] = ISNULL(@AnchorEntityID, [AnchorEntityID]),
        [FactorType] = ISNULL(@FactorType, [FactorType]),
        [SourceRelatedEntityID] = CASE WHEN @SourceRelatedEntityID_Clear = 1 THEN NULL ELSE ISNULL(@SourceRelatedEntityID, [SourceRelatedEntityID]) END,
        [SourceEntityID] = CASE WHEN @SourceEntityID_Clear = 1 THEN NULL ELSE ISNULL(@SourceEntityID, [SourceEntityID]) END,
        [FilterExpression] = CASE WHEN @FilterExpression_Clear = 1 THEN NULL ELSE ISNULL(@FilterExpression, [FilterExpression]) END,
        [Aggregation] = CASE WHEN @Aggregation_Clear = 1 THEN NULL ELSE ISNULL(@Aggregation, [Aggregation]) END,
        [AggregateFieldName] = CASE WHEN @AggregateFieldName_Clear = 1 THEN NULL ELSE ISNULL(@AggregateFieldName, [AggregateFieldName]) END,
        [TimeWindowID] = CASE WHEN @TimeWindowID_Clear = 1 THEN NULL ELSE ISNULL(@TimeWindowID, [TimeWindowID]) END,
        [RecencyDecayHalfLifeDays] = CASE WHEN @RecencyDecayHalfLifeDays_Clear = 1 THEN NULL ELSE ISNULL(@RecencyDecayHalfLifeDays, [RecencyDecayHalfLifeDays]) END,
        [ActionID] = CASE WHEN @ActionID_Clear = 1 THEN NULL ELSE ISNULL(@ActionID, [ActionID]) END,
        [ActionParamsJSON] = CASE WHEN @ActionParamsJSON_Clear = 1 THEN NULL ELSE ISNULL(@ActionParamsJSON, [ActionParamsJSON]) END,
        [ExecutionMode] = CASE WHEN @ExecutionMode_Clear = 1 THEN NULL ELSE ISNULL(@ExecutionMode, [ExecutionMode]) END,
        [IsExpensive] = ISNULL(@IsExpensive, [IsExpensive]),
        [MaxConcurrency] = CASE WHEN @MaxConcurrency_Clear = 1 THEN NULL ELSE ISNULL(@MaxConcurrency, [MaxConcurrency]) END,
        [RateLimitPerMinute] = CASE WHEN @RateLimitPerMinute_Clear = 1 THEN NULL ELSE ISNULL(@RateLimitPerMinute, [RateLimitPerMinute]) END,
        [CacheTTLSeconds] = CASE WHEN @CacheTTLSeconds_Clear = 1 THEN NULL ELSE ISNULL(@CacheTTLSeconds, [CacheTTLSeconds]) END,
        [SourceScoreModelID] = CASE WHEN @SourceScoreModelID_Clear = 1 THEN NULL ELSE ISNULL(@SourceScoreModelID, [SourceScoreModelID]) END,
        [RawDataType] = CASE WHEN @RawDataType_Clear = 1 THEN NULL ELSE ISNULL(@RawDataType, [RawDataType]) END,
        [NormalizationMethod] = CASE WHEN @NormalizationMethod_Clear = 1 THEN NULL ELSE ISNULL(@NormalizationMethod, [NormalizationMethod]) END,
        [NormalizationParamsJSON] = CASE WHEN @NormalizationParamsJSON_Clear = 1 THEN NULL ELSE ISNULL(@NormalizationParamsJSON, [NormalizationParamsJSON]) END,
        [OutputMin] = CASE WHEN @OutputMin_Clear = 1 THEN NULL ELSE ISNULL(@OutputMin, [OutputMin]) END,
        [OutputMax] = CASE WHEN @OutputMax_Clear = 1 THEN NULL ELSE ISNULL(@OutputMax, [OutputMax]) END,
        [HigherIsBetter] = ISNULL(@HigherIsBetter, [HigherIsBetter]),
        [PromotionState] = CASE WHEN @PromotionState_Clear = 1 THEN NULL ELSE ISNULL(@PromotionState, [PromotionState]) END,
        [LastValidatedAt] = CASE WHEN @LastValidatedAt_Clear = 1 THEN NULL ELSE ISNULL(@LastValidatedAt, [LastValidatedAt]) END,
        [CreatedByAgent] = CASE WHEN @CreatedByAgent_Clear = 1 THEN NULL ELSE ISNULL(@CreatedByAgent, [CreatedByAgent]) END,
        [DateField] = CASE WHEN @DateField_Clear = 1 THEN NULL ELSE ISNULL(@DateField, [DateField]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwFactors] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwFactors]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateFactor] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Factor table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateFactor]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateFactor];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateFactor
ON [${flyway:defaultSchema}].[Factor]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Factor]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[Factor] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Sonar: Factors */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateFactor] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Sonar: Factors */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Sonar: Factors
-- Item: spDeleteFactor
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Factor
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteFactor]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteFactor];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteFactor]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[Factor]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteFactor] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Sonar: Factors */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteFactor] TO [cdp_Developer], [cdp_Integration];

/* SQL text to delete unneeded entity fields (1 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='01BC22BE-E8C3-4C17-912B-FC2AF1E2DC03';

/* SQL text to update existing entity fields from schema (1 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='01BC22BE-E8C3-4C17-912B-FC2AF1E2DC03';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}';

